[tool.poetry]
name = "extism"
version = "0.1.0"
description = ""
authors = ["Zach Shipko <zachshipko@gmail.com>"]
license = "ISC"

[tool.poetry.dependencies]
python = "^3.7"
cffi = "^1.10.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
